"use client";
import {Check,Crown,GraduationCap,School} from "lucide-react";
import {useState} from "react";
import {formatPlanPrice,getPublicPlans} from "@/lib/billing/config";
import type {AccountType,PlanId} from "@/lib/billing/types";
import {CheckoutButton} from "./checkout-button";

const features:Record<PlanId,string[]>={student_free:["All core lessons and revision notes","Basic flashcards and worked solutions","10-question practice sets","Core progress and achievements"],student_plus_monthly:["AI-assisted feedback with fair-use controls","Personal revision planner","Advanced analytics and weekly reports","Unlimited custom sets and 20 generated papers monthly"],student_plus_annual:["Everything in Student Plus Monthly","Two months’ equivalent saving","One annual payment","Cancel renewal at any time"],teacher_free:["One active class","Up to 15 active students","Three active assignments","Basic class progress"],teacher_pro_monthly:["Multiple classes and up to 2,000 students","Advanced analytics and reports","Unlimited assignments within technical limits","Scheduling, exports and intervention insights"],teacher_pro_annual:["Everything in Teacher Pro Monthly","Save £100.88 compared with monthly","One annual payment","Cancel renewal at any time"]};
export function PricingTable({initial="student",currentPlan,demo=false}:{initial?:AccountType;currentPlan?:PlanId;demo?:boolean}){const[type,setType]=useState<AccountType>(initial);const plans=getPublicPlans(type);return <><div className="mx-auto mt-8 grid max-w-md grid-cols-2 rounded-2xl bg-[var(--surface-soft)] p-1" role="tablist" aria-label="Pricing audience"><button role="tab" aria-selected={type==="student"} onClick={()=>setType("student")} className={`flex min-h-11 items-center justify-center gap-2 rounded-xl font-black ${type==="student"?"bg-[var(--surface)] shadow":"text-muted"}`}><GraduationCap size={18}/>Students</button><button role="tab" aria-selected={type==="teacher"} onClick={()=>setType("teacher")} className={`flex min-h-11 items-center justify-center gap-2 rounded-xl font-black ${type==="teacher"?"bg-[var(--surface)] shadow":"text-muted"}`}><School size={18}/>Teachers</button></div><section className="mt-9 grid gap-5 lg:grid-cols-3" aria-label={`${type} plans`}>{plans.map((plan)=>{const annual=plan.billingInterval==="year";const current=currentPlan===plan.id;const monthlyEquivalent=annual?(plan.displayPricePence/12/100).toLocaleString("en-GB",{style:"currency",currency:"GBP"}):null;return <article key={plan.id} className={`card relative flex flex-col p-6 ${annual?"border-2 border-amber-400":current?"border-2 border-[var(--teal)]":""}`}>{annual?<span className="absolute right-4 top-4 flex items-center gap-1 rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-900"><Crown size={14}/>Best value</span>:null}<p className="font-black text-[var(--violet)]">{type==="student"?"STUDENT":"TEACHER"}</p><h2 className="mt-2 pr-20 text-2xl font-black">{plan.displayName.replace(/ Monthly| Annual/,"")}</h2><p className="mt-4 text-4xl font-black">{formatPlanPrice(plan.id)}</p><p className="mt-1 min-h-6 text-sm text-muted">{plan.billingInterval==="free"?"No card required":annual?`${monthlyEquivalent} per month equivalent`:"Billed monthly"}</p><ul className="my-6 flex-1 space-y-3">{features[plan.id].map(feature=><li key={feature} className="flex gap-2 text-sm font-bold"><Check className="mt-0.5 shrink-0 text-[var(--teal)]" size={17}/>{feature}</li>)}</ul>{current?<span className="flex min-h-12 items-center justify-center rounded-xl border-2 border-[var(--teal)] font-black text-[var(--teal)]">Current plan</span>:plan.billingInterval==="free"?<a href="/sign-up" className="flex min-h-12 items-center justify-center rounded-xl border font-black">Start free</a>:<CheckoutButton planId={plan.id} disabled={demo} label="Upgrade securely"/>}</article>})}</section><p className="mt-6 text-center text-sm leading-6 text-muted">Payments are handled securely by Stripe. Cancel through the hosted billing portal. Taxes may apply where legally required; Stripe confirms the final amount before payment.</p></>}
