import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/admin/auth";
import { writeAdminAudit } from "@/lib/admin/audit";
import { createAdminClient } from "@/lib/supabase/admin";
import { questionEditorSchema } from "@/lib/admin/validation";
const schema=z.object({status:z.enum(["draft","published","archived"])});
export async function PATCH(request:Request,{params}:{params:Promise<{questionId:string}>}){const actor=await requireAdmin(); if(!actor)return NextResponse.json({error:"Administrator access is required."},{status:403}); const parsed=schema.safeParse(await request.json()); if(!parsed.success)return NextResponse.json({error:"Invalid question status."},{status:400}); const {questionId}=await params; if(!actor.demo){const admin=createAdminClient(); const {data:current}=await admin.from("questions").select("id,status,version,prompt").eq("id",questionId).maybeSingle(); if(!current)return NextResponse.json({error:"Question not found."},{status:404}); await admin.from("content_versions").insert({entity_type:"question",entity_id:questionId,version:current.version,snapshot:current,changed_by:actor.userId}); const {error}=await admin.from("questions").update({status:parsed.data.status,archived_at:parsed.data.status==="archived"?new Date().toISOString():null,version:current.version+1}).eq("id",questionId); if(error)return NextResponse.json({error:"Question status could not be changed."},{status:500}); await writeAdminAudit(actor.userId,`question.${parsed.data.status}`,"question",questionId,{from:current.status,to:parsed.data.status});} return NextResponse.json({status:parsed.data.status});}
export async function PUT(request:Request,{params}:{params:Promise<{questionId:string}>}){const actor=await requireAdmin();if(!actor)return NextResponse.json({error:"Administrator access is required."},{status:403});const parsed=questionEditorSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Check the question, answer rule and marking fields."},{status:400});const{questionId}=await params;if(actor.demo)return NextResponse.json({questionId});const admin=createAdminClient();const{data:current}=await admin.from("questions").select("id,version,prompt,type,difficulty,marks,status,explanation").eq("id",questionId).maybeSingle();if(!current)return NextResponse.json({error:"Question not found."},{status:404});await admin.from("content_versions").insert({entity_type:"question",entity_id:questionId,version:current.version,snapshot:current,changed_by:actor.userId});const q=parsed.data;const{error}=await admin.from("questions").update({subtopic_id:q.subtopicId,type:q.type,difficulty:q.difficulty,prompt:{prompt:q.prompt},marks:q.marks,estimated_seconds:q.estimatedSeconds,calculator_allowed:q.calculatorAllowed,status:q.status,explanation:q.explanation,hints:q.hints,common_mistakes:q.commonMistakes,stimulus:q.stimulus,code_block:q.codeBlock,version:current.version+1}).eq("id",questionId);if(error)return NextResponse.json({error:"The question could not be updated."},{status:500});await admin.from("question_answer_rules").update({rule_type:q.ruleType,rule:q.answerRule as never,feedback:q.feedback}).eq("question_id",questionId);await writeAdminAudit(actor.userId,"question.updated","question",questionId,{version:current.version+1});return NextResponse.json({questionId});}
