"use client";

import { Archive, CheckCircle2, LoaderCircle, Plus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { AdminContentItem, ContentStatus } from "@/types/admin";

const kinds={course:"Courses",topic:"Topics",lesson:"Lessons",flashcard:"Flashcards",worked_solution:"Worked solutions"} as const;
export function ContentManager({initial}:{initial:AdminContentItem[]}){
  const [items,setItems]=useState(initial); const [kind,setKind]=useState<keyof typeof kinds>("course"); const [title,setTitle]=useState(""); const [detail,setDetail]=useState(""); const [parentId,setParentId]=useState(""); const [busy,setBusy]=useState(false); const [ready,setReady]=useState(false); const [error,setError]=useState<string>();
  useEffect(()=>{const frame=requestAnimationFrame(()=>setReady(true));return()=>cancelAnimationFrame(frame)},[]);
  const shown=useMemo(()=>items.filter((x)=>x.kind===kind),[items,kind]);
  async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError(undefined);const response=await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,title,detail,parentId:parentId||undefined})});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.error);setItems((all)=>[{id:body.id,kind,title,detail,status:"draft"},...all]);setTitle("");setDetail("")}
  async function status(id:string,next:ContentStatus){const response=await fetch("/api/admin/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({kind,id,status:next})});if(response.ok)setItems((all)=>all.map((x)=>x.id===id?{...x,status:next}:x))}
  return <div className="grid gap-6 xl:grid-cols-[14rem_1fr]"><nav aria-label="Content types" className="card h-fit p-3">{Object.entries(kinds).map(([id,label])=><button key={id} onClick={()=>setKind(id as keyof typeof kinds)} className={`min-h-11 w-full rounded-xl px-3 text-left font-black ${kind===id?"bg-violet-100 text-[var(--violet)] dark:bg-violet-500/15":"hover:bg-[var(--surface-soft)]"}`}>{label}</button>)}</nav><div><form onSubmit={create} className="card p-5"><h2 className="text-xl font-black">Add {kinds[kind].toLowerCase().replace(/s$/,"")}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-black">Title or front<input aria-label="Content title" disabled={!ready} required minLength={2} value={title} onChange={(e)=>setTitle(e.target.value)} className="mt-2 h-12 w-full rounded-xl border bg-[var(--surface)] px-4 font-bold disabled:opacity-60"/></label><label className="text-sm font-black">Parent ID {kind==="course"?"(not needed)":"(section or subtopic)"}<input aria-label="Parent ID" value={parentId} onChange={(e)=>setParentId(e.target.value)} className="mt-2 h-12 w-full rounded-xl border bg-[var(--surface)] px-4 font-mono text-sm"/></label><label className="text-sm font-black sm:col-span-2">Description, back or prompt<textarea aria-label="Content detail" value={detail} onChange={(e)=>setDetail(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border bg-[var(--surface)] p-4"/></label></div>{error?<p role="alert" className="mt-3 text-sm font-bold text-red-600">{error}</p>:null}<button disabled={busy||!ready} className="mt-4 flex min-h-11 items-center gap-2 rounded-xl bg-[var(--violet)] px-5 font-black text-white disabled:opacity-50">{busy?<LoaderCircle className="animate-spin"/>:<><Plus size={18}/>Add draft</>}</button></form><div className="mt-5 space-y-3">{shown.map((item)=><article key={item.id} className="card flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><h3 className="font-black">{item.title}</h3><span className="rounded-full bg-[var(--surface-soft)] px-2 py-1 text-xs font-black">{item.status}</span></div><p className="mt-1 max-w-2xl text-sm text-muted">{item.detail}</p></div><div className="flex gap-2">{item.status!=="published"?<button onClick={()=>status(item.id,"published")} className="grid size-10 place-items-center rounded-xl border text-teal-600" aria-label={`Publish ${item.title}`}><CheckCircle2 size={17}/></button>:null}{item.status!=="archived"?<button onClick={()=>status(item.id,"archived")} className="grid size-10 place-items-center rounded-xl border text-red-600" aria-label={`Archive ${item.title}`}><Archive size={17}/></button>:null}</div></article>)}</div></div></div>;
}
