"use client";

import { CheckCircle2, FileUp, LoaderCircle, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { questionCsvTemplate, questionJsonTemplate } from "@/lib/admin/import-validation";
import type { ImportValidation } from "@/types/admin";

export function ImportTool() {
  const [result,setResult]=useState<ImportValidation>(); const [busy,setBusy]=useState(false); const [error,setError]=useState<string>(); const [done,setDone]=useState<string>();
  async function choose(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError(undefined);setDone(undefined);if(file.size>1_000_000){setBusy(false);return setError("Import files must be smaller than 1 MB.");}const text=await file.text();const format=file.name.toLowerCase().endsWith(".json")?"json":"csv";const response=await fetch("/api/admin/imports/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text,format})});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.error);setResult(body);}
  async function commit(){if(!result?.valid.length||result.invalid.length)return;setBusy(true);const response=await fetch("/api/admin/imports/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows:result.valid.map((r)=>r.value),confirmed:true})});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.error);setDone(`${body.inserted} questions imported; ${body.duplicates} duplicates skipped.`);}
  function template(format:"csv"|"json"){const blob=new Blob([format==="csv"?questionCsvTemplate:questionJsonTemplate],{type:format==="csv"?"text/csv":"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`bytewise-question-template.${format}`;a.click();URL.revokeObjectURL(url);}
  return <div className="space-y-6"><section className="card p-6"><div className="flex gap-3"><FileUp className="text-[var(--violet)]"/><div><h2 className="text-xl font-black">Upload and validate</h2><p className="mt-1 text-sm text-muted">CSV or JSON · maximum 1 MB and 250 rows · nothing saves before confirmation.</p></div></div><div className="mt-5 flex flex-wrap gap-3"><label className="flex min-h-12 cursor-pointer items-center gap-2 rounded-xl bg-[var(--violet)] px-5 font-black text-white"><FileUp size={18}/>{busy?"Reading…":"Choose file"}<input aria-label="Question import file" type="file" accept=".csv,.json,text/csv,application/json" onChange={choose} className="sr-only"/></label><button type="button" onClick={()=>template("csv")} className="min-h-12 rounded-xl border bg-[var(--surface)] px-5 font-black">Download CSV template</button><button type="button" onClick={()=>template("json")} className="min-h-12 rounded-xl border bg-[var(--surface)] px-5 font-black">Download JSON template</button></div>{error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>:null}</section>{result?<section className="card p-6"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-teal-50 p-4 text-teal-900 dark:bg-teal-500/10 dark:text-teal-100"><CheckCircle2/><p className="mt-2 text-2xl font-black">{result.valid.length} valid</p></div><div className="rounded-xl bg-amber-50 p-4 text-amber-950 dark:bg-amber-500/10 dark:text-amber-100"><TriangleAlert/><p className="mt-2 text-2xl font-black">{result.invalid.length} invalid</p></div></div>{result.invalid.length?<div className="mt-5 space-y-2">{result.invalid.map((row)=><div key={row.row} className="rounded-xl border border-red-200 p-3"><p className="font-black">Row {row.row}</p><ul className="mt-1 text-sm text-red-700">{row.errors.map((item)=><li key={item}>• {item}</li>)}</ul></div>)}</div>:null}<h3 className="mt-6 font-black">Preview</h3><div className="mt-3 space-y-2">{result.valid.slice(0,5).map((row)=><div key={row.row} className="soft-card p-3"><span className="text-xs font-black text-muted">ROW {row.row}</span><p className="font-bold">{row.value.prompt}</p></div>)}</div><button onClick={commit} disabled={busy||!result.valid.length||Boolean(result.invalid.length)} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[var(--teal)] px-5 font-black text-slate-950 disabled:opacity-40">{busy?<LoaderCircle className="animate-spin"/>:"Confirm transactional import"}</button>{done?<p className="mt-4 rounded-xl bg-teal-50 p-4 font-black text-teal-900">{done}</p>:null}</section>:null}</div>;
}
