"use client";

import { ArrowRight, BookOpen, Brain, Flame, Sparkles, Target, TrendingDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { applyLocalHistory } from "@/lib/progress/demo-progress";
import type { PracticeResult } from "@/types/practice";
import type { ProgressSnapshot } from "@/types/progress";

export function ProgressDashboard({ initial }: { initial: ProgressSnapshot }) {
  const [snapshot, setSnapshot] = useState(initial);
  useEffect(() => { const timer = window.setTimeout(() => { const history = JSON.parse(window.localStorage.getItem("bytewise:attempt-history") ?? "[]") as PracticeResult[]; setSnapshot(applyLocalHistory(initial, history)); }, 0); return () => clearTimeout(timer); }, [initial]);
  const average = Math.round(snapshot.topics.reduce((sum, topic) => sum + topic.score, 0) / Math.max(1, snapshot.topics.length));
  const weakest = useMemo(() => [...snapshot.topics].sort((a, b) => a.score - b.score)[0], [snapshot.topics]);
  const maxActivity = Math.max(...snapshot.activity.map((day) => day.questions), 1);

  return <>
    <section className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]">
      <div className="relative overflow-hidden rounded-[1.75rem] bg-[linear-gradient(120deg,#6847e8,#4977ed)] p-7 text-white sm:p-9"><div className="absolute -right-12 -top-16 size-64 rounded-full border-[38px] border-white/10" /><div className="relative"><p className="font-black text-violet-100">COURSE MASTERY</p><div className="mt-4 flex flex-wrap items-end gap-5"><span className="text-6xl font-black">{average}%</span><span className="mb-2 rounded-full bg-white/15 px-3 py-1 text-sm font-black">{average >= 75 ? "Mastered" : average >= 55 ? "Secure" : "Developing"}</span></div><p className="mt-4 max-w-xl text-lg leading-8 text-violet-100">Built from accuracy, challenge, recency and repeated evidence—not just completed lessons.</p></div></div>
      <aside className="card p-6"><p className="text-sm font-black text-[var(--coral)]">BEST NEXT STEP</p><div className="mt-3 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-[var(--surface-soft)] text-2xl">{weakest.icon}</span><div><h2 className="font-black">Strengthen {weakest.title}</h2><p className="text-sm text-muted">{weakest.score}% · {weakest.label}</p></div></div><p className="mt-4 leading-7 text-muted">{weakest.explanation}</p><Link href={`/practise?topic=${weakest.slug}&mode=adaptive`} className="mt-5 flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--violet)] px-4 font-black text-white"><Sparkles size={18} />Start adaptive set</Link></aside>
    </section>

    <section aria-label="Progress summary" className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MiniStat icon={<Flame />} label="Current streak" value={`${snapshot.currentStreak} days`} note={`Best: ${snapshot.bestStreak} days`} /><MiniStat icon={<Target />} label="Recent accuracy" value={`${snapshot.recentAccuracy}%`} note="Across recent marked sets" /><MiniStat icon={<Brain />} label="Questions answered" value={String(snapshot.totalQuestions)} note="Practice evidence collected" /><MiniStat icon={<BookOpen />} label="Secure topics" value={String(snapshot.topics.filter((topic) => topic.score >= 55).length)} note={`of ${snapshot.topics.length} sampled topics`} /></section>

    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-black text-[var(--violet)]">TOPIC INSIGHTS</p><h2 className="mt-1 text-2xl font-black">Why your mastery looks like this</h2></div><p className="max-w-xl text-sm leading-6 text-muted">Scores move gradually as new evidence is blended with your longer-term record.</p></div><div className="mt-5 grid gap-5 xl:grid-cols-3">{snapshot.topics.map((topic) => <article key={topic.slug} className="card p-5"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-[var(--surface-soft)] text-2xl">{topic.icon}</span><span className={`flex items-center gap-1 rounded-full px-3 py-1 text-xs font-black ${topic.trend === "up" ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-200" : topic.trend === "down" ? "bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-200" : "bg-[var(--surface-soft)] text-muted"}`}>{topic.trend === "up" ? <TrendingUp size={14} /> : topic.trend === "down" ? <TrendingDown size={14} /> : null}{topic.trend === "steady" ? "Steady" : topic.trend === "up" ? "Improving" : "Needs retrieval"}</span></div><h3 className="mt-4 text-xl font-black">{topic.title}</h3><div className="mt-3 flex items-end justify-between"><span className="text-3xl font-black" style={{ color: topic.colour }}>{topic.score}%</span><span className="text-sm font-black text-muted">{topic.label}</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-[var(--surface-soft)]"><div className="h-full rounded-full" style={{ width: `${topic.score}%`, background: topic.colour }} /></div><p className="mt-4 text-sm leading-6 text-muted">{topic.explanation}</p><p className="mt-3 text-xs font-bold text-muted">{topic.questionsSeen} questions seen · {topic.accuracy}% recent accuracy</p><Link href={`/practise?topic=${topic.slug}`} className="mt-4 inline-flex items-center gap-2 font-black text-[var(--violet)]">Practise topic <ArrowRight size={16} /></Link></article>)}</div></section>

    <section className="card mt-8 p-6"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-sm font-black text-muted">LAST 7 DAYS</p><h2 className="mt-1 text-xl font-black">Practice activity</h2></div><span className="font-black text-[var(--violet)]">{snapshot.activity.reduce((sum, day) => sum + day.questions, 0)} questions</span></div><div className="mt-6 flex h-44 items-end gap-3" aria-hidden="true">{snapshot.activity.map((day) => <div key={day.date} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-black text-muted">{day.questions}</span><div className="w-full max-w-12 rounded-t-xl bg-[var(--violet)]" style={{ height: `${Math.max(8, day.questions / maxActivity * 120)}px` }} /><span className="text-xs font-bold text-muted">{new Intl.DateTimeFormat("en-GB", { weekday: "short" }).format(new Date(`${day.date}T12:00:00`))}</span></div>)}</div><p className="sr-only">In the last seven days you answered {snapshot.activity.reduce((sum, day) => sum + day.questions, 0)} questions. Your busiest day had {maxActivity} questions.</p></section>
  </>;
}

function MiniStat({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: string; note: string }) { return <article className="card p-5"><span className="text-[var(--violet)]">{icon}</span><p className="mt-4 text-sm font-black text-muted">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-muted">{note}</p></article>; }
