import type { Metadata } from "next";
import { ArrowRight, BookOpenCheck, ChartNoAxesCombined, Users } from "lucide-react";
import Link from "next/link";
import { Breadcrumbs } from "@/components/content/breadcrumbs";
import { CreateClassForm } from "@/components/teacher/create-class-form";
import { JoinClassForm } from "@/components/teacher/join-class-form";
import { getTeacherClasses } from "@/lib/teacher/repository";

export const metadata: Metadata = { title: "Classes" };
export default async function ClassesPage() { const classes = await getTeacherClasses(); return <main id="main-content" tabIndex={-1} className="mx-auto max-w-7xl px-5 pb-20 pt-20 sm:px-8 lg:pt-10"><Breadcrumbs items={[{ label: "Classes" }]} /><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-black text-[var(--teal)]">CLASSES & ASSIGNMENTS</p><h1 className="mt-2 text-4xl font-black tracking-tight">Teach with useful signals</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-muted">Create classes, publish focused work and see the learning evidence that helps you plan next steps.</p></div><Link href="/teacher" className="flex min-h-11 items-center gap-2 rounded-xl border bg-[var(--surface)] px-4 font-black"><ChartNoAxesCombined size={18} />Teacher dashboard</Link></div><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_20rem]"><div className="space-y-6"><CreateClassForm /><section><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">Your classes</h2><span className="text-sm font-bold text-muted">{classes.filter((c)=>!c.archived).length} active</span></div><div className="grid gap-4 md:grid-cols-2">{classes.map((item) => <Link key={item.id} href={`/classes/${item.id}`} className="card group p-6 transition hover:-translate-y-1"><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-100 text-[var(--violet)] dark:bg-violet-500/15"><BookOpenCheck /></span>{item.archived ? <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">Archived</span> : <ArrowRight className="text-muted transition group-hover:translate-x-1" />}</div><h3 className="mt-5 text-xl font-black">{item.name}</h3><p className="mt-1 text-sm text-muted">{item.courseTitle}</p><div className="mt-5 flex flex-wrap gap-4 text-sm font-bold text-muted"><span className="flex items-center gap-1"><Users size={16} />{item.students.length} students</span><span>{item.assignments.length} assignments</span></div></Link>)}</div></section></div><JoinClassForm /></div></main>; }
