import{expect,test}from"@playwright/test";
test("pricing separates student and teacher plans with accurate prices",async({page})=>{await page.goto("/pricing");await expect(page.getByRole("heading",{name:"Student Plus"}).first()).toBeVisible();await expect(page.getByText("£5.99",{exact:true})).toBeVisible();await expect(page.getByText("£49.00",{exact:true})).toBeVisible();await page.getByRole("tab",{name:"Teachers"}).click();await expect(page.getByRole("heading",{name:"Teacher Pro"}).first()).toBeVisible();await expect(page.getByText("£24.99",{exact:true})).toBeVisible();await expect(page.getByText("£199.00",{exact:true})).toBeVisible();});
test("demo pricing previews paid plans without starting checkout",async({page})=>{await page.goto("/pricing");const previews=page.getByRole("button",{name:"Preview only"});await expect(previews).toHaveCount(2);await expect(previews.first()).toBeDisabled();});
test("billing page explains the current free demo plan",async({page})=>{await page.goto("/billing");await expect(page.getByRole("heading",{name:"Student Free"})).toBeVisible();await expect(page.getByText("Billing is preview-only in demo mode.",{exact:false})).toBeVisible();await expect(page.getByRole("link",{name:"Compare plans"})).toBeVisible();});

test("teacher accounts default to teacher-only billing choices",async({page})=>{await page.context().addCookies([{name:"bytewise-demo-role",value:"teacher",url:"http://127.0.0.1:3100"}]);await page.goto("/pricing");await expect(page.getByRole("tab",{name:"Teachers"})).toHaveAttribute("aria-selected","true");await expect(page.getByText("£24.99",{exact:true})).toBeVisible();await expect(page.getByText("£5.99",{exact:true})).toHaveCount(0);await page.goto("/billing");await expect(page.getByRole("heading",{name:"Teacher Free"})).toBeVisible();await expect(page.getByText("teacher account · active",{exact:true})).toBeVisible();});

test("checkout cancellation preserves free access and offers safe routes",async({page})=>{await page.goto("/billing/cancelled");await expect(page.getByRole("heading",{name:"Checkout cancelled"})).toBeVisible();await expect(page.getByText("Your free access and existing work are unchanged.",{exact:false})).toBeVisible();await expect(page.getByRole("link",{name:"Return to pricing"})).toBeVisible();await expect(page.getByRole("link",{name:"Dashboard"})).toBeVisible();});

test("checkout return never claims access before trusted confirmation",async({page})=>{await page.route("**/api/billing/status**",async(route)=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({confirmed:false,subscription:null})}));await page.goto("/billing/success?session_id=cs_test_mock");await expect(page.getByRole("heading",{name:"Thanks — confirming your payment"})).toBeVisible();await expect(page.getByText("verified webhook or secure server check",{exact:false})).toBeVisible();await expect(page.getByText("Your plan is active",{exact:false})).toHaveCount(0);});

test("demo checkout API cannot create a Stripe session",async({request},testInfo)=>{const headers={"x-forwarded-for":`playwright-${testInfo.project.name}`};for(const body of [{planId:"student_plus_monthly"},{planId:"teacher_pro_monthly"},{planId:"price_attacker"}]){const response=await request.post("/api/billing/checkout",{data:body,headers});expect(response.status()).toBe(401);const json=await response.json();expect(json.url).toBeUndefined();expect(json.error).toContain("real account");}});

test("pricing remains responsive and exposes honest fair-use wording",async({page})=>{await page.goto("/pricing");await expect(page.getByText("20 generated papers monthly",{exact:false})).toBeVisible();const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:document.documentElement.clientWidth}));expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.viewport);});
