import type { Metadata } from "next";
import { AlertTriangle, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/content/breadcrumbs";
import { getClassInsights, getTeacherClass } from "@/lib/teacher/repository";
import { getCurrentAccount } from "@/lib/auth/account";
import { hasEntitlement } from "@/lib/billing/server";
import { UpgradePanel } from "@/components/billing/upgrade-panel";

export const metadata: Metadata = { title: "Class analytics" };
export default async function AnalyticsPage({ params }: { params: Promise<{ classId: string }> }) { const { classId } = await params; const account=await getCurrentAccount(); const allowed=Boolean(account&&(account.userId.startsWith("demo-")||await hasEntitlement(account.userId,"teacher.advanced_analytics"))); if(!allowed)return <main id="main-content" tabIndex={-1} className="px-5 pb-20 pt-20 lg:pt-10"><UpgradePanel accountType="teacher" title="Turn class evidence into a teaching plan" description="Teacher Pro adds topic weakness analysis, class-level patterns and intervention insights while keeping individual learning data private." returnHref={`/classes/${classId}`}/></main>; const [item, insights] = await Promise.all([getTeacherClass(classId), getClassInsights(classId)]); if (!item) notFound(); const weakest = [...insights].sort((a,b)=>a.averageMastery-b.averageMastery)[0]; return <main id="main-content" tabIndex={-1} className="mx-auto max-w-6xl px-5 pb-20 pt-20 sm:px-8 lg:pt-10"><Breadcrumbs items={[{ label: "Classes", href: "/classes" }, { label: item.name, href: `/classes/${classId}` }, { label: "Analytics" }]} /><p className="font-black text-[var(--teal)]">CLASS ANALYTICS</p><h1 className="mt-2 text-4xl font-black tracking-tight">Plan from the pattern, not a ranking</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-muted">Aggregates highlight common gaps while avoiding public student comparisons.</p>{weakest ? <section className="mt-8 flex gap-4 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950 dark:bg-amber-500/10 dark:text-amber-100"><AlertTriangle className="shrink-0" /><div><h2 className="font-black">Common next step: {weakest.title}</h2><p className="mt-1 text-sm">Class average is {weakest.averageMastery}%. Consider a short retrieval activity before moving on.</p></div></section> : null}<section className="mt-8 card p-6"><h2 className="text-2xl font-black">Topic mastery</h2><div className="mt-6 space-y-6">{insights.map((topic) => <article key={topic.topicId}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-black">{topic.title}</h3><span className="text-sm font-bold">{topic.averageMastery}% average · {topic.secureStudents}/{topic.studentCount} secure</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[var(--surface-soft)]"><div className="h-full rounded-full bg-[var(--violet)]" style={{ width: `${topic.averageMastery}%` }} /></div></article>)}</div></section><aside className="mt-6 flex gap-3 rounded-2xl bg-slate-950 p-5 text-slate-200"><ShieldCheck className="shrink-0 text-teal-300" /><p className="text-sm leading-6"><strong className="text-white">Privacy by design.</strong> This view returns aggregate mastery and completion only. It does not include student email addresses, raw answers or activity outside this class.</p></aside></main>; }
