import type { Metadata } from "next";
import { ArrowLeft, ArrowRight, BookOpen, Clock3, Lightbulb, ShieldAlert, TextQuote } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/content/breadcrumbs";
import { LessonProgressButton } from "@/components/content/lesson-progress-button";
import { getLesson } from "@/lib/content/repository";

type Params = Promise<{ topicSlug: string; lessonSlug: string }>;
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const value = await params; const { lesson } = await getLesson(value.topicSlug, value.lessonSlug); return { title: lesson?.title ?? "Lesson" }; }

const calloutIcons = { definition: TextQuote, tip: Lightbulb, warning: ShieldAlert };
export default async function LessonPage({ params }: { params: Params }) {
  const value = await params; const { topic, lesson } = await getLesson(value.topicSlug, value.lessonSlug); if (!topic || !lesson) notFound();
  const index = topic.lessons.findIndex((item) => item.id === lesson.id); const previous = topic.lessons[index - 1]; const next = topic.lessons[index + 1];
  return <main id="main-content" tabIndex={-1} className="mx-auto max-w-5xl px-5 pb-20 pt-20 sm:px-8 lg:pt-10"><Breadcrumbs items={[{ label: "Learn", href: "/learn" }, { label: topic.title, href: `/learn/${topic.slug}` }, { label: lesson.title }]} /><div className="grid gap-7 lg:grid-cols-[1fr_17rem]"><article><header className="card p-6 sm:p-8"><span className="inline-flex items-center gap-2 text-sm font-black text-[var(--violet)]"><BookOpen size={17} /> LESSON {index + 1} OF {topic.lessons.length}</span><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{lesson.title}</h1><p className="mt-3 text-lg leading-8 text-muted">{lesson.summary}</p><p className="mt-5 flex items-center gap-2 text-sm font-extrabold text-muted"><Clock3 size={17} /> About {lesson.estimatedMinutes} minutes</p></header><div className="mt-6 space-y-6">{lesson.sections.map((section) => <section key={section.id} className="card p-6 sm:p-8"><h2 className="text-2xl font-black">{section.heading}</h2><div className="mt-4 space-y-4">{section.body.map((paragraph) => <p key={paragraph} className="text-[1.04rem] leading-8 text-muted">{paragraph}</p>)}</div>{section.callout && (() => { const Icon = calloutIcons[section.callout.type]; return <aside className="mt-6 flex gap-3 rounded-2xl border bg-[var(--surface-soft)] p-4"><Icon className="mt-0.5 shrink-0 text-[var(--violet)]" size={20} /><div><p className="font-black">{section.callout.title}</p><p className="mt-1 leading-6 text-muted">{section.callout.text}</p></div></aside>; })()}</section>)}</div><nav aria-label="Lesson navigation" className="mt-7 grid gap-3 sm:grid-cols-2">{previous ? <Link href={`/learn/${topic.slug}/${previous.slug}`} className="card flex min-h-14 items-center gap-3 p-4 font-black"><ArrowLeft size={18} />{previous.title}</Link> : <span />}{next ? <Link href={`/learn/${topic.slug}/${next.slug}`} className="card flex min-h-14 items-center justify-end gap-3 p-4 text-right font-black">{next.title}<ArrowRight size={18} /></Link> : <Link href={`/learn/${topic.slug}`} className="card flex min-h-14 items-center justify-end gap-3 p-4 font-black">Back to topic <ArrowRight size={18} /></Link>}</nav></article><aside className="lg:sticky lg:top-7 lg:self-start"><section className="card p-5"><p className="text-sm font-extrabold text-muted">LESSON PROGRESS</p><div className="mt-4"><LessonProgressButton lessonId={lesson.id} /></div><div className="mt-5 border-t pt-5"><p className="font-black">Up next</p><p className="mt-1 text-sm leading-6 text-muted">{next?.title ?? "Review this topic's flashcards"}</p></div></section></aside></div></main>;
}
