import type { Metadata } from "next";
import { BookOpenCheck, FileWarning, History, ShieldCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminNav } from "@/components/admin/admin-nav";
import { Breadcrumbs } from "@/components/content/breadcrumbs";
import { requireAdmin } from "@/lib/admin/auth";
import { getAdminOverview } from "@/lib/admin/repository";
export const metadata:Metadata={title:"Admin dashboard"};
export default async function AdminPage(){if(!await requireAdmin())notFound();const data=await getAdminOverview();const published=data.questions.filter((q)=>q.status==="published").length;return <main id="main-content" className="mx-auto max-w-7xl px-5 pb-20 pt-20 sm:px-8 lg:pt-10"><Breadcrumbs items={[{label:"Admin"}]}/><AdminNav/><p className="font-black text-[var(--coral)]">ADMIN DASHBOARD</p><h1 className="mt-2 text-4xl font-black tracking-tight">Keep the learning library trustworthy</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-muted">Manage content, review quality signals and make sensitive changes through audited server controls.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Published questions",published,BookOpenCheck,"var(--violet)"],["Open reports",data.reports.filter((r)=>r.status==="open").length,FileWarning,"var(--coral)"],["Managed users",data.users.length,UsersRound,"var(--blue)"],["Recent changes",data.audit.length,History,"var(--teal)"]].map(([label,value,Icon,colour])=>{const I=Icon as typeof ShieldCheck;return <article key={String(label)} className="card p-5"><I style={{color:String(colour)}}/><p className="mt-3 text-3xl font-black">{String(value)}</p><p className="text-sm font-bold text-muted">{String(label)}</p></article>})}</section><section className="mt-8 grid gap-4 md:grid-cols-3"><Link href="/admin/questions/new" className="card p-6 transition hover:-translate-y-1"><h2 className="text-xl font-black">Add a question</h2><p className="mt-2 text-sm leading-6 text-muted">Create protected answers, explanations and marking rules.</p></Link><Link href="/admin/imports" className="card p-6 transition hover:-translate-y-1"><h2 className="text-xl font-black">Validate an import</h2><p className="mt-2 text-sm leading-6 text-muted">Preview CSV or JSON rows before one transactional save.</p></Link><Link href="/admin/reports" className="card p-6 transition hover:-translate-y-1"><h2 className="text-xl font-black">Review reports</h2><p className="mt-2 text-sm leading-6 text-muted">Resolve content concerns while preserving an audit trail.</p></Link></section><section className="mt-8 card p-6"><h2 className="text-2xl font-black">Recent audit activity</h2><div className="mt-4 divide-y">{data.audit.slice(0,5).map((entry)=><div key={entry.id} className="py-4"><p className="font-black">{entry.action.replaceAll("."," ")}</p><p className="mt-1 text-sm text-muted">{entry.actorLabel} · {entry.entityType} · {new Date(entry.createdAt).toLocaleString("en-GB")}</p></div>)}</div></section></main>}
