import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "./auth";
import { demoAdminQuestions, demoAdminReports, demoAdminUsers, demoAudit, demoContent } from "./demo-admin";
import type { AdminContentItem, AdminQuestion, AdminReport, AdminUser, AuditEntry } from "@/types/admin";

function promptText(prompt: unknown) { if(typeof prompt==="string") return prompt; if(prompt&&typeof prompt==="object"&&"prompt" in prompt) return String((prompt as {prompt:unknown}).prompt); return "Untitled question"; }

export async function getAdminQuestions(): Promise<AdminQuestion[]> {
  const actor=await requireAdmin(); if(!actor||actor.demo) return demoAdminQuestions; const admin=createAdminClient();
  const [{data:questions},{data:stats},{data:reports}]=await Promise.all([admin.from("questions").select("id,prompt,type,difficulty,marks,status,subtopic_id").order("updated_at",{ascending:false}).limit(250),actor.supabase.rpc("admin_question_performance"),admin.from("question_reports").select("question_id")]);
  const statMap=new Map((stats??[]).map((s)=>[s.question_id,s])); return (questions??[]).map((q)=>{const stat=statMap.get(q.id); return {id:q.id,prompt:promptText(q.prompt),type:q.type as AdminQuestion["type"],difficulty:q.difficulty,marks:q.marks,topic:"Course topic",status:q.status,attempts:Number(stat?.attempts??0),averagePercent:stat?Number(stat.average_percent):undefined,reportCount:(reports??[]).filter((r)=>r.question_id===q.id).length};});
}
export async function getAdminReports(): Promise<AdminReport[]> {
  const actor=await requireAdmin(); if(!actor||actor.demo) return demoAdminReports; const admin=createAdminClient(); const {data}=await admin.from("question_reports").select("id,question_id,category,details,status,internal_notes,created_at").order("created_at",{ascending:false}); const ids=(data??[]).flatMap((r)=>r.question_id?[r.question_id]:[]); const {data:questions}=ids.length?await admin.from("questions").select("id,prompt").in("id",ids):{data:[]}; return (data??[]).map((r)=>({id:r.id,questionId:r.question_id??undefined,category:r.category,details:r.details,status:r.status,internalNotes:r.internal_notes??undefined,createdAt:r.created_at,questionPrompt:promptText(questions?.find((q)=>q.id===r.question_id)?.prompt)}));
}
export async function getAdminUsers(): Promise<AdminUser[]> { const actor=await requireAdmin(); if(!actor||actor.demo) return demoAdminUsers; const {data}=await actor.supabase.rpc("admin_users"); return (data??[]).map((u)=>({id:u.user_id,displayName:u.display_name,role:u.roles.includes("admin")?"admin":u.roles.includes("teacher")?"teacher":"student"})); }
export async function getAuditEntries(): Promise<AuditEntry[]> { const actor=await requireAdmin(); if(!actor||actor.demo) return demoAudit; const {data}=await createAdminClient().from("admin_audit_logs").select("id,actor_id,action,entity_type,entity_id,metadata,created_at").order("created_at",{ascending:false}).limit(100); return (data??[]).map((a)=>({id:a.id,action:a.action,entityType:a.entity_type,entityId:a.entity_id??undefined,actorLabel:a.actor_id===actor.userId?"You":"Administrator",metadata:a.metadata,createdAt:a.created_at})); }
export async function getAdminContent(): Promise<AdminContentItem[]> { const actor=await requireAdmin(); if(!actor||actor.demo) return demoContent; const admin=createAdminClient(); const [{data:courses},{data:topics},{data:lessons},{data:cards},{data:solutions}]=await Promise.all([admin.from("courses").select("id,title,description,published"),admin.from("topics").select("id,title,description,status"),admin.from("lessons").select("id,title,summary,status"),admin.from("flashcards").select("id,front,hint,status"),admin.from("worked_solutions").select("id,title,prompt,status")]); return [...(courses??[]).map((x)=>({id:x.id,kind:"course" as const,title:x.title,detail:x.description,status:(x.published?"published":"draft") as AdminContentItem["status"]})),...(topics??[]).map((x)=>({id:x.id,kind:"topic" as const,title:x.title,detail:x.description,status:x.status})),...(lessons??[]).map((x)=>({id:x.id,kind:"lesson" as const,title:x.title,detail:x.summary,status:x.status})),...(cards??[]).map((x)=>({id:x.id,kind:"flashcard" as const,title:x.front,detail:x.hint??"No hint",status:x.status})),...(solutions??[]).map((x)=>({id:x.id,kind:"worked_solution" as const,title:x.title,detail:x.prompt,status:x.status}))]; }

export async function getAdminOverview() { const [questions,reports,users,content,audit]=await Promise.all([getAdminQuestions(),getAdminReports(),getAdminUsers(),getAdminContent(),getAuditEntries()]); return {questions,reports,users,content,audit}; }
export async function getAdminQuestionForEdit(id:string){const actor=await requireAdmin();if(!actor)return null;if(actor.demo){const q=demoAdminQuestions.find((x)=>x.id===id)??demoAdminQuestions[0];return{questionId:id,prompt:q.prompt,type:q.type,difficulty:["foundation","standard","stretch"].includes(q.difficulty)?q.difficulty:"standard",marks:q.marks,estimatedSeconds:60,status:q.status==="archived"?"draft":q.status,explanation:"Review and improve the explanation shown after submission.",feedback:"Clear, actionable marking feedback.",answerRule:{kind:"exact",acceptable:["answer"]}};}const admin=createAdminClient();const[{data:q},{data:rule}]=await Promise.all([admin.from("questions").select("id,prompt,type,difficulty,marks,estimated_seconds,status,explanation").eq("id",id).maybeSingle(),admin.from("question_answer_rules").select("rule_type,rule,feedback").eq("question_id",id).maybeSingle()]);if(!q)return null;return{questionId:q.id,prompt:promptText(q.prompt),type:q.type,difficulty:q.difficulty,marks:q.marks,estimatedSeconds:q.estimated_seconds,status:q.status==="archived"?"draft":q.status,explanation:q.explanation,feedback:rule?.feedback??"",answerRule:rule?.rule??{kind:"exact",acceptable:[""]}};}
