import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/admin/auth";
import { writeAdminAudit } from "@/lib/admin/audit";
import { contentSchema } from "@/lib/admin/validation";
import { createAdminClient } from "@/lib/supabase/admin";
const statusSchema=z.object({kind:z.enum(["course","topic","lesson","flashcard","worked_solution"]),id:z.string().min(3),status:z.enum(["draft","published","archived"])});
const slug=(text:string)=>text.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);
export async function POST(request:Request){const actor=await requireAdmin(); if(!actor)return NextResponse.json({error:"Administrator access is required."},{status:403}); const parsed=contentSchema.safeParse(await request.json()); if(!parsed.success)return NextResponse.json({error:"Check the content title and parent ID."},{status:400}); if(actor.demo)return NextResponse.json({id:`demo-${parsed.data.kind}-${Date.now()}`},{status:201}); const admin=createAdminClient(); const x=parsed.data; let result:{id:string}|null=null; let error:unknown;
  if(x.kind==="course"){({data:result,error}=await admin.from("courses").insert({qualification_id:"00000000-0000-0000-0000-000000000001",exam_board_id:"00000000-0000-0000-0000-000000000011",slug:slug(x.title),title:x.title,description:x.detail}).select("id").single());}
  else if(!x.parentId)return NextResponse.json({error:"A valid parent ID is required for this content type."},{status:400});
  else if(x.kind==="topic"){({data:result,error}=await admin.from("topics").insert({specification_section_id:x.parentId,slug:slug(x.title),title:x.title,description:x.detail}).select("id").single());}
  else if(x.kind==="lesson"){({data:result,error}=await admin.from("lessons").insert({subtopic_id:x.parentId,slug:slug(x.title),title:x.title,summary:x.detail}).select("id").single());}
  else if(x.kind==="flashcard"){({data:result,error}=await admin.from("flashcards").insert({subtopic_id:x.parentId,front:x.title,back:x.detail}).select("id").single());}
  else {({data:result,error}=await admin.from("worked_solutions").insert({subtopic_id:x.parentId,title:x.title,prompt:x.detail,final_answer:"Add final answer before publishing."}).select("id").single());}
  if(error||!result)return NextResponse.json({error:"The content could not be created. Check its parent and uniqueness."},{status:400}); await writeAdminAudit(actor.userId,"content.created",x.kind,result.id); return NextResponse.json({id:result.id},{status:201});}
export async function PATCH(request:Request){const actor=await requireAdmin(); if(!actor)return NextResponse.json({error:"Administrator access is required."},{status:403}); const parsed=statusSchema.safeParse(await request.json()); if(!parsed.success)return NextResponse.json({error:"Invalid content status."},{status:400}); if(!actor.demo){const admin=createAdminClient(); const x=parsed.data; const result=x.kind==="course"?await admin.from("courses").update({published:x.status==="published"}).eq("id",x.id).select("id").maybeSingle():x.kind==="topic"?await admin.from("topics").update({status:x.status}).eq("id",x.id).select("id").maybeSingle():x.kind==="lesson"?await admin.from("lessons").update({status:x.status}).eq("id",x.id).select("id").maybeSingle():x.kind==="flashcard"?await admin.from("flashcards").update({status:x.status}).eq("id",x.id).select("id").maybeSingle():await admin.from("worked_solutions").update({status:x.status}).eq("id",x.id).select("id").maybeSingle(); if(result.error||!result.data)return NextResponse.json({error:"Content not found."},{status:404}); await writeAdminAudit(actor.userId,`content.${x.status}`,x.kind,x.id);} return NextResponse.json({status:parsed.data.status});}
