import type { Metadata } from "next";
import { AlertCircle, BookOpen, GraduationCap } from "lucide-react";
import { Breadcrumbs } from "@/components/content/breadcrumbs";
import { TopicCard } from "@/components/content/topic-card";
import { getActiveCourseContent } from "@/lib/content/repository";

export const metadata: Metadata = { title: "Learn" };
export default async function LearnPage() {
  const course = await getActiveCourseContent();
  return <main id="main-content" tabIndex={-1} className="mx-auto max-w-7xl px-5 pb-16 pt-20 sm:px-8 lg:pt-10"><Breadcrumbs items={[{ label: "Learn" }]} /><section className="relative overflow-hidden rounded-[1.75rem] bg-[linear-gradient(120deg,#6847e8,#4977ed)] p-6 text-white sm:p-9"><div className="absolute -right-14 -top-20 size-64 rounded-full border-[38px] border-white/10" /><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-black"><GraduationCap size={16} /> YOUR COURSE</span><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">{course.title}</h1><p className="mt-3 max-w-2xl leading-7 text-violet-100">{course.description}</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-xl bg-white/15 px-3 py-2 text-sm font-bold">{course.qualification}</span><span className="rounded-xl bg-white/15 px-3 py-2 text-sm font-bold">{course.examBoard}</span><span className="rounded-xl bg-white/15 px-3 py-2 text-sm font-bold">{course.topics.length} sample topics</span></div></div></section><div className="mt-6 flex gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-100"><AlertCircle className="mt-0.5 shrink-0" size={19} /><p><strong>Representative content:</strong> this learning path demonstrates the platform and does not yet cover the complete official specification.</p></div><div className="mb-5 mt-9 flex items-center gap-3"><BookOpen className="text-[var(--violet)]" /><h2 className="text-2xl font-black">Choose a topic</h2></div>{course.topics.length ? <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{course.topics.map((topic) => <TopicCard key={topic.id} topic={topic} />)}</section> : <div className="card p-8 text-center"><p className="text-xl font-black">Content is being prepared for this course</p><p className="mt-2 text-muted">Choose OCR GCSE in Settings to explore the representative Phase 2 lessons.</p></div>}</main>;
}
