"use client";

import { Archive, KeyRound, LoaderCircle, UserMinus } from "lucide-react";
import { useState } from "react";

export function ClassActions({ classId, students }: { classId: string; students: Array<{ id: string; displayName: string }> }) {
  const [code, setCode] = useState<string>(); const [busy, setBusy] = useState<string>(); const [removed, setRemoved] = useState<string[]>([]); const [archived, setArchived] = useState(false);
  async function rotate() { setBusy("code"); const response = await fetch(`/api/classes/${classId}/join-code`, { method: "POST" }); const body = await response.json(); if (response.ok) setCode(body.joinCode); setBusy(undefined); }
  async function remove(id: string) { setBusy(id); const response = await fetch(`/api/classes/${classId}/members/${id}`, { method: "DELETE" }); if (response.ok) setRemoved((value) => [...value, id]); setBusy(undefined); }
  async function archive() { setBusy("archive"); const response = await fetch(`/api/classes/${classId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ archived: true }) }); if (response.ok) setArchived(true); setBusy(undefined); }
  return <div className="space-y-5"><section className="soft-card p-5"><h2 className="font-black">Joining code</h2><p className="mt-2 text-sm text-muted">Rotate the code if it was shared outside the intended class. The old code stops working immediately.</p><button onClick={rotate} disabled={busy === "code"} className="mt-4 flex min-h-11 items-center gap-2 rounded-xl border bg-[var(--surface)] px-4 font-black">{busy === "code" ? <LoaderCircle className="animate-spin" /> : <KeyRound size={18} />}Rotate code</button>{code ? <div className="mt-3 rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold text-slate-300">NEW CODE — SHOWN ONCE</p><code className="mt-1 block text-2xl font-black tracking-[0.25em]">{code}</code></div> : null}</section><section className="card p-5"><h2 className="text-xl font-black">Students</h2><ul className="mt-4 divide-y">{students.filter((s) => !removed.includes(s.id)).map((student) => <li key={student.id} className="flex items-center justify-between gap-3 py-3"><span className="font-bold">{student.displayName}</span><button onClick={() => remove(student.id)} disabled={busy === student.id} aria-label={`Remove ${student.displayName}`} className="flex min-h-10 items-center gap-2 rounded-xl px-3 text-sm font-black text-red-600 hover:bg-red-50">{busy === student.id ? <LoaderCircle size={17} className="animate-spin" /> : <UserMinus size={17} />}Remove</button></li>)}</ul></section><button onClick={archive} disabled={archived || busy === "archive"} className="flex min-h-11 items-center gap-2 rounded-xl border px-4 font-black text-muted disabled:opacity-60"><Archive size={18} />{archived ? "Class archived" : "Archive class"}</button></div>;
}
