"use client";

import { Check, Copy, LoaderCircle, Plus, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type Created = { id: string; name: string; courseTitle?: string };
export function CreateClassForm() {
  const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [ready, setReady] = useState(false); const [error, setError] = useState<string>(); const [created, setCreated] = useState<Created>(); const [joinCode, setJoinCode] = useState<string>(); const [copied, setCopied] = useState(false); useEffect(() => { const frame = requestAnimationFrame(() => setReady(true)); return () => cancelAnimationFrame(frame); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(undefined); const response = await fetch("/api/classes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, courseId: "10000000-0000-0000-0000-000000000001" }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setError(body.error ?? "The class could not be created."); setCreated(body.class); setJoinCode(body.joinCode); setName(""); }
  async function copyCode() { if (!joinCode) return; await navigator.clipboard.writeText(joinCode); setCopied(true); }
  return <section className="card p-6" aria-labelledby="create-class-title"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-100 text-[var(--violet)] dark:bg-violet-500/15"><Plus /></span><div><h2 id="create-class-title" className="text-xl font-black">Create a class</h2><p className="mt-1 text-sm text-muted">A joining code is shown once, then only its final two characters remain visible.</p></div></div><form onSubmit={submit} className="mt-5 flex flex-col gap-3 sm:flex-row"><label className="flex-1 text-sm font-black">Class name<input disabled={!ready} required minLength={2} maxLength={80} value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Year 10 Computer Science" className="mt-2 h-12 w-full rounded-xl border bg-[var(--surface)] px-4 font-bold disabled:opacity-60" /></label><button disabled={busy || !ready} className="mt-auto flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[var(--violet)] px-5 font-black text-white disabled:opacity-50">{busy ? <LoaderCircle className="animate-spin" /> : <><Plus size={18} />Create class</>}</button></form>{error ? <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p> : null}{created && joinCode ? <div className="mt-5 rounded-2xl border-2 border-[var(--teal)] bg-teal-50 p-5 dark:bg-teal-500/10"><div className="flex items-center gap-2 font-black text-teal-800 dark:text-teal-200"><ShieldCheck size={20} />{created.name} is ready</div><p className="mt-3 text-sm text-muted">Share this code securely with the intended students. Rotating it immediately invalidates this one.</p><div className="mt-3 flex flex-wrap items-center gap-3"><code data-testid="new-join-code" className="rounded-xl bg-slate-950 px-5 py-3 text-2xl font-black tracking-[0.28em] text-white">{joinCode}</code><button type="button" onClick={copyCode} className="flex min-h-11 items-center gap-2 rounded-xl border bg-[var(--surface)] px-4 font-black">{copied ? <Check size={18} /> : <Copy size={18} />}{copied ? "Copied" : "Copy"}</button><Link href={`/classes/${created.id}`} className="font-black text-[var(--violet)]">Open class →</Link></div></div> : null}</section>;
}
